import "./globals.css";

// components
import MainNav from "@/components/MainNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" foxified="">
      <body>
        <div className="flex">
          <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
          <div className="w-full max-w-[1130px] px-[15px] mx-auto bg-pink-50/10">
            <header>header</header>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
